---
title: "Union Document Notebook"
output: 
  pdf_document:
    latex_engine: pdflatex
  github_document:
    toc: true
    toc_depth: 2
---

# Union of documents

## Loading libraries

```{r message=FALSE, warning=FALSE}

# lib = where to save the library  (zonder = default)

package_list <- c("data.table", "tidyverse", "naniar", "stringr", "readr",  "dplyr", "magrittr", "readxl", "writexl", "sjmisc", "tidyr", "rmarkdown"
                  )

for (pkg in package_list) {
  if (pkg %in% rownames(.packages()) == FALSE)
  {library(pkg, character.only = TRUE)}

}
```

## Data creation and loading

```{r message=FALSE, warning=FALSE}

barometer_DGZ <- read.csv("../Data/CleanedData/barometer_DGZ.csv")
barometer_ARSIA <- read.csv("../Data/CleanedData/barometer_ARSIA.csv")
barometer_GD <- read.csv("../Data/CleanedData/barometer_GD.csv")
barometer_Ireland <- read.csv("../Data/CleanedData/barometer_Ireland.csv")
barometer_PathoSense <- read.csv("../Data/CleanedData/barometer_PathoSense.csv")
                                


```

## Combine data to one format and add column with month and year for Tableau

```{r message=FALSE, warning=FALSE}
barometer_Tableau <- rbind(barometer_DGZ, barometer_ARSIA, barometer_GD, barometer_Ireland, barometer_PathoSense) %>% 
  dplyr::mutate(
    Month = month(as.Date(Floored_date)),
    Year = year(as.Date(Floored_date))
    ) %>%
  dplyr::rename(
   LabReference = Lab_reference,
   FlooredDate = Floored_date,
   FarmIdentifier = Farm_ID, 
   DiagnosticTest = Diagnostic_test,
   SampleType = Sample_type
  ) %>%
  dplyr::select(-X)

```

## Save file (with current date)

```{r message=FALSE, warning=FALSE}
#Generate current date, give basic filename/path, combine, and safe 

current_date <- format(Sys.Date(), "%Y-%m-%d")
base_filename <- "barometer_combined"
folder_path <- "../Data/CleanedData/"
new_filename <- paste0(folder_path, base_filename, "_", current_date, ".csv")

write.csv(barometer_Tableau, file = new_filename, row.names = TRUE) 

```
